### PR TITLE
[FEAT] distinctUntilChanged for optionals

### PR DESCRIPTION
**Pull request by pikciu**

### CODE REVIEW

**Comment by ashfurrow** [comment]
Looks great! Could you add a change log entry when you have a chance? Some tests would be great, but I can add those afterward (gotta fix Travis anyway😉).

**Comment by ashfurrow** [comment]
Awesome, thanks! I've fixed CI in https://github.com/RxSwiftCommunity/RxOptional/pull/22 – could I ask you to pull the latest from master to your local branch, the push to your fork? That will update this pull request and it should be all ✅

**Comment by thanegill** [comment]
@pikciu Sorry this has taken a while for me to get around too. Can I ask that you add `distinctUntilChanged` to `Driver` as well. Once that is done and there are test I'll merge! 😊

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
