### PR TITLE
[WIP] Fixes for Xcode 9.3 and Swift 4.1

### PR DESCRIPTION
**Pull request by hartbit**
Stupid me, I can't get the project to build. What's the procedure? I've done a `carthage build` but I'm still getting a `No such module 'RxCocoa'` error. Any idea?

### CODE REVIEW

**Comment by freak4pc** [comment]
I’m not sure there’s any good sense to add 41 and Xcode 9.3 fixes until GM is out, since RxSwift itself will probably change to resolve some build issues

**Comment by hartbit** [comment]
Can we keep this open until 4.1 comes out?

**Comment by freak4pc** [comment]
Yup, absolutely !

**Comment by alanzeino** [comment]
There's only one 4.1 issue with RxSwift that I've seen (https://github.com/ReactiveX/RxSwift/issues/1598). This fix works as expected in our codebase so I would recommend just merging now since I doubt that Swift 4.1 will change much between now and final release.

**Comment by freak4pc** [comment]
@alanzeino In general I agree with you but we've been relatively burnt in the past by older Swift releases when trying to "run" after Swift releases and its eventually not super worthwhile. Since you tried it on a very large project I feel relatively more confident with this. 

I'll try to spare some time to review this over the weekend and see if we can push this forward. 

Thanks for the feedback!

**Comment by freak4pc** [comment]
Thanks @hartbit, and welcome :)

**Pull request merged**
