### PR TITLE
Add support for SPM

### PR DESCRIPTION
**Pull request by minuscorp**
The new usage for release the version would be `swift run rocket {VERSION_TO_RELEASE}`, i.e. `swift run rocket 1.0.0` This will create a tag where the test and development dependencies are hidden, I also added the typical steps for releasing the Cococapods version to trunk. Need to validate this though.

### CODE REVIEW

**Comment by minuscorp** [comment]
Ready to review @ashfurrow

**Comment by minuscorp** [comment]
Tag + release?

**Comment by fassko** [comment]
After @ashfurrow will give me access I will release it.

**Comment by minuscorp** [comment]
I've seen that the after step of pushing to trunk will fail because it will find that the podspec has the same version if it's not changed before launching rocket command

**Comment by freak4pc** [comment]
Tagged and released as 4.1.0

```
 🎉  Congrats

 🚀  RxOptional (4.1.0) successfully published
 📅  October 22nd, 11:17
 🌎  https://cocoapods.org/pods/RxOptional
 👍  Tell your friends!
```

**Pull request merged**
