### PR TITLE
Support Carthage

### PR DESCRIPTION
**Pull request by zhouhao27**
Add Carthage in swift-3.0 branch.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Can anyone more familiar with Carthage take a look? Seems like the swift-3.0 branch isn't building on CI anyway, so don't worry about the red check.

**Comment by zhouhao27** [comment]
I'll check. But I'm not familiar with CI.

**Comment by muukii** [comment]
Not good to commit the source code of RxSwift.
It is solved by the project configuration, such as the Alamofire.

So, I created new PR.
https://github.com/RxSwiftCommunity/RxOptional/pull/28

**Comment by ashfurrow** [comment]
I'm going to close this in favour of #28, thanks again for opening this pull request @zhouhao27.

**Pull request closed without merging**
