### PR TITLE
CI Fix

### PR DESCRIPTION
**Pull request by ashfurrow**
Two parts:

- Specifies CocoaPods version (should've been doing this anyway)
- Fix for https://github.com/Quick/Nimble/issues/280

### CODE REVIEW

**Comment by orta** [comment]
The optimal 1.0 podfile for this is:

```ruby
use_frameworks!

target 'RxOptional Examples' do
  pod 'RxOptional', :path => '../'
  pod 'RxSwift', '~> 2.0'
  pod 'RxCocoa', '~> 2.0'
  
  target 'RxOptional Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble', :git => 'https://github.com/ashfurrow/Nimble.git', :branch => 'podspec-update'
  end
end
```

**Comment by ashfurrow** [comment]
Mmm good point.

**Comment by orta** [comment]
That's a niggle, good to merge regardless of that 👍

**Comment by ashfurrow** [comment]
Nah, I noticed `Podfile.lock` was missing, might as well add that here too. Might prevent future CI breaks.

**Comment by ashfurrow** [comment]
Hmm, now it's red.

**Comment by ashfurrow** [comment]
Reproduced locally, looks like it's iPhone 4S-only, maybe a 32-bit problem.

**Comment by orta** [comment]
potentially useful aside: `cache: cocoapods` is happening on travis too

**Comment by ashfurrow** [comment]
I'm not really up for dealing with weird CI-only failures, I've merged in 665b1a2 (the last green commit in this PR) and a subsequent addition of `Podfile.lock` (went [green on CI](https://travis-ci.org/RxSwiftCommunity/RxOptional/builds/124419577)).

**Pull request closed without merging**
