### PR TITLE
Update Cartfile dependency to RxSwift 3.0.0-beta.2

### PR DESCRIPTION
**Pull request by tonyarnold**

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by tonyarnold** [comment]
Is it worthwhile breaking off a new point release for this change? I can specify `master` in my Cartfile, but it would be better to keep version pinning in place.

**Comment by ashfurrow** [comment]
Aye, I'll get to it later unless you beat me to it. Just needs a changelog entry.

**Comment by tonyarnold** [comment]
So uhh… how do I do a release? I keep getting access denied when pushing the version bump to the changelog/podspec and new tag.

I assume that direct pushes to `master` are disabled?

**Comment by ashfurrow** [comment]
Great question! I'm tied up today. It I'll see what's going on – might be a GitHub permissions problem. Thanks for hanging in there!

--  
Ash Furrow
Sent with Airmail

**Comment by ashfurrow** [comment]
Cool, pushed 👍 Permissions should be fixed now too!

**Pull request merged**
