### PR TITLE
RxOptional 4.0.0

### PR DESCRIPTION
**Pull request by freak4pc**
This release will provide support for RxSwift 5 (and thus, also Xcode 10.2).

I've also removed the watchOS test target. I'm a bit confused why it was there since:

1. We never ran it in any CI configuration.
2. Quick and Nimble don't even build on watchOS. Meaning, we can't even run these tests. 🤷‍♂️

Aaaanyways.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Ah, wait, the `E` -> `Element` looks like an RxSwift change haha. Well anyway, it's great 👍

**Comment by freak4pc** [comment]
It is green:  I just updated the CHANGELOG, but let's wait for it anyways just to play it safe :) 

https://circleci.com/gh/RxSwiftCommunity/RxOptional/62

**Comment by freak4pc** [comment]
@ashfurrow 

> Ah, wait, the E -> Element looks like an RxSwift change haha. Well anyway, it's great 👍

Yup, was a tedious change regardless 😅

**Comment by tonyarnold** [comment]
Waitaminute how did your almost identical changes pass and mine didn’t? Freaking CircleCI… 🦀

**Comment by freak4pc** [comment]
I think the main thing was I removed the "restore cache" portion until the first time tests pass, to run over the existing cache. I think basically what we discussed in the other thread.

**Comment by tonyarnold** [comment]
Well, I'm just glad you got it all working! Thanks for taking over 😁

**Pull request merged**
