### PR TITLE
Add support for RxSwift 5.0.0

### LINKED ISSUE #74: Cannot update to RxSwift 5.x when using Carthage
When including this extension via Carthage, an update checks out RxSwift 3.0.0 beta 1, and not RxSwift 5.0.0 as expected. 

I'd hazard a guess that the version restriction in the `Cartfile` needs to be lifted from `4.3.1` to `5.0.0`.

### PR DESCRIPTION
**Pull request by tonyarnold**
Not sure if you agree with bumping the major version, but it makes sense to me from a SemVer perspective. Let me know if you need anything else!

Fixes #74.

### CODE REVIEW

**Comment by tonyarnold** [comment]
Yeah, I'm out. I'm happy to fix the remaining deprecations, but I've battled CircleCI long enough - I've got to get on with other work. Someone else will need to take over.

**Comment by ashfurrow** [comment]
I can try to take a look this weekend if no one gets to it before then. Thanks Tony!

**Comment by freak4pc** [comment]
I'm taking care of RxSwiftExt today/tomorrow and can then look into this as well if Ash won't get here first.

**Comment by ashfurrow** [comment]
Thanks @freak4pc! I think you're more familiar with Carthage than I am, which this repo's CI uses, so I appreciate your help :bow:

**Comment by freak4pc** [comment]
I’ve has problems with that caching script as well. Not really sure what gives but after the build is successful and you push back to the cache it should be ok.

**Comment by tonyarnold** [comment]
I _think_ it's just my lack of familiarity with CircleCI - I've not used it for a long time. Feel free to pull my PR to bits - if I managed to figure it out, I was going to rewrite the history on this branch before merge anyhow. Thanks, folks!

**Comment by freak4pc** [comment]
I should have some free time tomorrow to poke into this. I've just fixed a similar issue in RxSwiftExt which was even more painful (much more code, targets, subspecs, tests, etc.)

**Comment by ashfurrow** [comment]
Yeah, Circle CI 2.0's new caching strategy is kind of bonkers. To bust its cache, you need to change the cache keys in the Circle config file (this is why they're prefixed with `v1-`, so you can have `v2`, `v3`, etc as you need to bust the cache). Like I said, kind of bonkers.

**Comment by freak4pc** [comment]
Option 2 is basically removing the "restore cache" portion while working on this branch so it constantly overrides the cache. Then at the end you just put that restore cache section back.

**Comment by tonyarnold** [comment]
It does seem bonkers that the cache doesn't refresh in a meaningful way when it is changed. Or is this a failure of Carthage to detect that the binaries in `Carthage/Build/**/*` _need_ to be rebuilt (I wouldn't think so, it's perfectly capable of detecting when the underlying toolchain has changed locally).

**Pull request closed without merging**
