### PR TITLE
Rename Observbale+Optional.swift to Observable+Optional.swift

### PR DESCRIPTION
**Pull request by sendyhalim**

### CODE REVIEW

**Comment by ashfurrow** [comment]
:grimacing: good catch, thanks a lot :bow:

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by sendyhalim** [comment]
@ashfurrow Sure thanks!

**Comment by thanegill** [comment]
Guess I fat fingered that. It needs to be changed it the Xcode project as well. @sendyhalim

**Comment by sendyhalim** [comment]
@thanegill oh yes, I will submit another PR, gimme a minute

**Comment by ashfurrow** [comment]
:grimacing: that's my fault, too. Should have waited for CI to pass – send a PR when you can, no worries!

**Comment by sendyhalim** [comment]
Hi, I've cloned the repo and opened it with xcode + running tests, everything seems fine, am I missing something? :D

screen shot 2016-03-16 at 02 47 06

**Comment by thanegill** [comment]
This is what I see:
screen shot 2016-03-15 at 12 54 48 pm

**Comment by ashfurrow** [comment]
@sendyhalim What is the output from `git status`? Have you made any commits and not pushed yet?

**Comment by ashfurrow** [comment]
Ah, no never mind, this is me :sweat_smile: The project is created based on the podspec, so we all just need to re-run `pod install` to re-generate :tada:

**Comment by sendyhalim** [comment]
@ashfurrow @thanegill weird, have you run `pod install`?

**Comment by sendyhalim** [comment]
@ashfurrow ah ok, I was planning to re-install xcode lol, thought it was an xcode bug XD

**Pull request merged**
