### PR TITLE
Support Swift Package Manager

### PR DESCRIPTION
**Pull request by goodocy**
Support Swift Package Manager
In Swift Package Manager, the platform referred to the podspec.
Support `swift test`

**Test way**
run `swift test`

### CODE REVIEW

**Comment by goodocy** [comment]
Oh... CI does not support directory change.
I'll change it as before.

**Comment by minuscorp** [comment]
can we get this reviewed? cc @ashfurrow

**Comment by ashfurrow** [comment]
Looks like a few merge conflicts to be resolve first, too 👍

**Comment by minuscorp** [comment]
I'll look into it tomorrow (CET time)

**Comment by minuscorp** [comment]
I didn't have a single moment to review this😰 I'll try on Monday 🙇🏻‍♂️

**Comment by minuscorp** [comment]
Can we consider using https://github.com/shibapm/Rocket for filtering out test targets and dependencies in release tags?

**Comment by ashfurrow** [comment]
Sure! We should definitely try new tools and processes like this. These open source repositories are the perfect place for this kind of thing, since others can see how we did it 👍

**Comment by minuscorp** [comment]
I will propose the new workflow ASAP, in the mean time this could be merged or just wait a little bit while I propose the new PR, as you prefer!

**Comment by minuscorp** [comment]
Fixed in #83

**Comment by goodocy** [comment]
@minuscorp Thank you for your support. 😃 
I will support the rocket.

**Comment by minuscorp** [comment]
@goodocy can we close this now? 😄

**Pull request closed without merging**
